from collections import namedtuple

const = namedtuple('const', 
                        ['EXCEL_FILE_FOLDER',
                         'JSON_KEY_FILE_NAME',
                         'JSON_KEY_FILE_SCOPE',
                         'SPREADSHEET_URL',
                         'SHEET_NAME',
                         'READ_START_HEADER',
                         'READ_HEADER_LIST',
                         'EXCEPT_COL_LIST',
                         'EXCEPT_WORDS',
                         'FIXED_EXPENSE_WORDS',
                         'STR_EXCEPT_CONTENTS_LIST',
                        ]
        )

CONSTS = const(
                        EXCEL_FILE_FOLDER = 'excel',
                        JSON_KEY_FILE_NAME = 'credential.json',
                        JSON_KEY_FILE_SCOPE = [
                        'https://spreadsheets.google.com/feeds',
                        'https://www.googleapis.com/auth/drive',
                        ],
                        SPREADSHEET_URL = 'https://docs.google.com/spreadsheets/d/1gVMAMnPW9TkXxmOjjS1jZ5-hKbg9hxIkoj-Bp-yYtxI/edit?usp=sharing',
                        SHEET_NAME = 'autoGeneratedSheet',
                        READ_START_HEADER = '이용일',
                        READ_HEADER_LIST = ['이용일', '이용가맹점', '원금', '적립예정'],
                        EXCEPT_COL_LIST = ['I'],
                        EXCEPT_WORDS = [ 
                        '버스', '지하철', '동부생명보험', '맞춤서비스수수료', 
                        '메리츠화재해상보험주식회사', '한화손해보험', '롯데손해보험주식회사', '삼성화재해상보험' 
                        ],
                        FIXED_EXPENSE_WORDS = [
                        '예스코_자동이체', 
                        'KT인터넷제휴 납부',
                        'KT통신요금 자동납부',
                        '한국전력공사',
                        '아파트 관리비',
                        'LH임대료',
                        'ETAX',
                        ],
                        STR_EXCEPT_CONTENTS_LIST = '제외된 내역 리스트',
         )
