from collections import namedtuple

const = namedtuple('const', 
                        ['excelFileFolder',
                         'jsonKeyfileName',
                         'jsonKeyfileScope',
                         'spreadsheetUrl',
                         'sheetName',
                        'readStartHeader',
                        'readHeaderList',
                        'exceptColList',
                        'exceptWords',
                        'fixedExpenseWords'
                        ]
        )

CONSTS = const(
                        'excel', # excelFileFolder
                        'my-financial-ledger-64c9734e9900.json', # jsonKeyfileName
                        [
                        'https://spreadsheets.google.com/feeds',
                        'https://www.googleapis.com/auth/drive',
                        ], # jsonKeyfileScope
                        'https://docs.google.com/spreadsheets/d/1gVMAMnPW9TkXxmOjjS1jZ5-hKbg9hxIkoj-Bp-yYtxI/edit?usp=sharing', # spreadsheetUrl
                        'autoGeneratedSheet', # sheetName
                        '이용일', # readStartHeader
                        ['이용일', '이용가맹점', '원금', '적립예정'], # readHeaderList
                        ['I'], # exceptColList
                        [ 
                        '버스', '지하철', '동부생명보험', '맞춤서비스수수료', 
                        '메리츠화재해상보험주식회사', '한화손해보험', '롯데손해보험주식회사', '삼성화재해상보험' 
                        ], # exceptWords
                        [
                        '예스코_자동이체', 
                        'KT인터넷제휴 납부',
                        'KT통신요금 자동납부',
                        '한국전력공사',
                        '아파트 관리비',
                        'LH임대료',
                        'ETAX',
                        ] # fixedExpenseWords
         )
